#include "AMRSimulation.hpp"
// #include <unordered_map>
// #include <unordered_set>

int AMRSimulation::evaluate_field_uniform_grid(double t) {
    // get reduced xs, reduced_ws from each species
    // combine reduced x, reduced_ws
    std::vector<double> reduced_xs, reduced_ws;
    for (auto &species : species_list) {
        species->get_reduced_xs_ws();
        reduced_xs.insert( reduced_xs.end(), species->reduced_xs.begin(), species->reduced_xs.end());
        reduced_ws.insert( reduced_ws.end(), species->reduced_ws.begin(), species->reduced_ws.end());
    }

// In order to calculate density rho, calculate electric field only generated by each species first
// save to files 

    if (iter_num % n_steps_diag == 0) {
        for (auto &species : species_list) {
            cout << "save " << species->species_name << " data." <<endl;
            std::vector<double> pure_xs_cpy (species->reduced_xs);
            std::vector<double> pure_es(species->reduced_xs.size());
            (*calculate_e)(pure_es.data(), species->reduced_xs.data(), species->reduced_xs.size(),
                    pure_xs_cpy.data(), species->reduced_ws.data(), species->reduced_xs.size() );

            // save the pure es to file 
            std::ofstream pure_x_file;
            std::ofstream pure_e_file;
            pure_x_file.open(sim_dir + "simulation_output/"  + species->species_name + "/pure_xs/xs_" + std::to_string(iter_num), std::ios::out | std::ios::binary); 
            pure_e_file.open(sim_dir + "simulation_output/"  + species->species_name + "/pure_es/es_"  + std::to_string(iter_num), std::ios::out | std::ios::binary);

            std::cout << "#pure_xs " << species->reduced_xs.size() << std::endl;
            std::cout << "#pure_es " << pure_es.size() << std::endl;

            if (!pure_x_file | !pure_e_file) {
                cout << "Unable to open reduced_xs data files" << endl;
                return 1;
            }

            assert(species->reduced_xs.size() == pure_es.size());
            for (int ii = 0; ii < pure_es.size(); ++ii) {
                double x = species->reduced_xs[ii];
                double e = pure_es[ii];
                pure_x_file.write((char *) &x, sizeof(double));
                pure_e_file.write((char *) &e, sizeof(double));
            }

            if (!pure_x_file.good() | !pure_e_file.good()) {
                cout << "Error occurred reduced_xs data files." << endl;
                return 1;
            }
            pure_x_file.close();
            pure_e_file.close();

        }
    }


// for two-species, electrons and ions have the same kernel, 
// the diff in the charge (q_ws) in code

    // duplicate reduced x
    std::vector<double> reduced_xs_cpy (reduced_xs);
    // evaluate reduced e
    std::vector<double> reduced_es(reduced_ws.size());
    (*calculate_e)(reduced_es.data(), reduced_xs.data(), reduced_xs.size(),
                 reduced_xs_cpy.data(), reduced_ws.data(), reduced_xs.size() );
    if (use_external_field) {
        (*calculate_e_external)(reduced_es.data(), reduced_xs.data(), reduced_xs.size(), t);
    }

    // check sizes: 
    cout << "The final reduced_xs size = " << reduced_xs.size() << endl;
    for (size_t this_sp = 0; this_sp < species_list.size(); this_sp++) {
        cout << "for the " << this_sp << "th species, its reduced_xs size = " << species_list[this_sp]->reduced_xs.size() << endl;
    }


    if (iter_num % n_steps_diag == 0) {
        // save the general reduce_es to file 
        std::ofstream reduced_x_file;
        std::ofstream reduced_e_file;
        reduced_x_file.open(sim_dir + "simulation_output/"  + "/reduce_xs/xs_" + std::to_string(iter_num), std::ios::out | std::ios::binary); 
        reduced_e_file.open(sim_dir + "simulation_output/"  + "/reduced_es/es_"  + std::to_string(iter_num), std::ios::out | std::ios::binary);

        std::cout << "#reduced_xs " << reduced_xs.size() << std::endl;
        std::cout << "#reduced_es " << reduced_es.size() << std::endl;

        if (!reduced_x_file | !reduced_e_file) {
            cout << "Unable to open reduced_xs data files" << endl;
            return 1;
        }

        assert(reduced_xs.size() == reduced_es.size());
        for (int ii = 0; ii < reduced_xs.size(); ++ii) {
            double x = reduced_xs[ii];
            double e = reduced_es[ii];
            reduced_x_file.write((char *) &x, sizeof(double));
            reduced_e_file.write((char *) &e, sizeof(double));
        }

        if (!reduced_x_file.good() | !reduced_e_file.good()) {
            cout << "Error occurred reduced_xs data files." << endl;
            return 1;
        }

        reduced_x_file.close();
        reduced_e_file.close();
    }


// For amr, distribute reduced es here to each species
// then in each species it will distribute again
    size_t start_ind = 0;
    for (auto &species : species_list) {
        species->get_reduced_es(reduced_es.data() + start_ind);
        start_ind += species->reduced_xs.size();
    }
    need_gather = true;

#if TESTFLAG
    outFile << "Reduced xs and es for each species: " << std::endl;
    for (int i = 0; i < N_sp; i++) {
        outFile << species_list[i]->species_name << "  , reduced_xs:  size = " << species_list[i]->reduced_xs.size() << endl;
        for (int j = 0; j < species_list[i]->reduced_xs.size(); j++) {
            outFile << setprecision(15) << species_list[i]->reduced_xs[j]  << "  ";
        }
        outFile << endl;
        outFile << species_list[i]->species_name << "  , reduced_ws:  size = " << species_list[i]->reduced_ws.size() << endl;
        for (int j = 0; j < species_list[i]->reduced_ws.size(); j++) {
            outFile << setprecision(15) << species_list[i]->reduced_ws[j]  << "  ";
        }
        outFile << endl;
        outFile << species_list[i]->species_name << "  , reduced_es:  size = " << species_list[i]->sort_es.size() << endl;
        for (int j = 0; j < species_list[i]->sort_es.size(); j++) {
            outFile << setprecision(15) << species_list[i]->sort_es[j]  << "  ";
        }
        outFile << endl;

        outFile << species_list[i]->species_name << "  , general reduced_xs:  size = " << reduced_xs.size() << endl;
        for (int j = 0; j < reduced_xs.size(); j++) {
            outFile << setprecision(15) << reduced_xs[j]  << "  ";
        }
        outFile << endl;

        outFile << species_list[i]->species_name << "  , general reduced_ws:  size = " << reduced_ws.size() << endl;
        for (int j = 0; j < reduced_ws.size(); j++) {
            outFile << setprecision(15) << reduced_ws[j]  << "  ";
        }
        outFile << endl;

        outFile << species_list[i]->species_name << "  , e compare to farsight :  size = " << reduced_es.size() << endl;
        for (int j = 0; j < reduced_es.size(); j++) {
            outFile << setprecision(15) << reduced_es[j]  << "  ";
        }
        outFile << endl;
    }
#endif
    return 0;
}

int AMRSimulation::evaluate_field(std::vector<double>& es_local, std::vector<double>& xs_local, std::vector<double>& q_ws_local, double t) {

    std::vector<double> xtemp_cpy(xs_local), xtemp_cpy2(xs_local);
    (*calculate_e)(es_local.data(), xtemp_cpy.data(), es_local.size(),
                    xtemp_cpy2.data(), q_ws_local.data(), xtemp_cpy.size());
    if (use_external_field) {
        (*calculate_e_external)(es_local.data(), xs_local.data(), es.size(), t);
    }
    return 0;
}
